Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/02/2019
Var
// Seção de Declarações das variáveis 
a,b,aux:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(a,b)
aux<-a
a<-b
b<-aux
escreva(a,b,aux)

Fimalgoritmo