Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2019
Var
// Seção de Declarações das variáveis 
C,F:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("DIGITE TEMPERATURA EM GRAUS F:")
leia(F)
C<-(F-32)*(5/9)
escreva(C)
Fimalgoritmo