Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2019
Var
// Seção de Declarações das variáveis 
V,R,H:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite h e r:")
leia(R)
leia(H)
V<-3,14*(R*R)*H
escreva(V)

Fimalgoritmo