Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/03/2019
Var
// Seção de Declarações das variáveis 
reais,dolar,cotacao:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a quantidade de Reais:")
leia(reais)
escreva("Digite a cotação do Dólar:")
leia(cotacao)
dolar<-cotacao*reais
escreva("O valor em dolar eh:",dolar)

Fimalgoritmo