Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/03/2019
Var
// Seção de Declarações das variáveis 
reais,dolar,cotacao:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor em dolares:")
leia(dolar)
escreva("Qual a cotação do Dolar:")
leia(cotacao)
reais<-dolar*cotacao
escreva("Valor em Reais eh:",reais)



Fimalgoritmo