Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/03/2019
Var
// Seção de Declarações das variáveis 
comprimento,largura,altura,volume:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(comprimento,largura,altura)
volume<-largura*altura*largura
escreva(volume)

Fimalgoritmo