Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/03/2019
Var
// Seção de Declarações das variáveis 
a,b,c,d,produto,soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("DIGITE 4 VALORES":)
leia(a,b,c,d)
produto<-a+c
soma<-

Fimalgoritmo